# Page settings

baseurl = "https://joymon.github.io/single-page-resume/"
languageCode = "en-us"
title = "Joy George Kunjikkuru"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Pavel Kanyshev"
# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # itâ€™s quick and easy to change the styling and colour scheme.

    styles = "styles-1.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Joy George Kunjikkuru"
        tagline = "Solutions Architect"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

    # Education section
    [params.education]
        enable = true
        title = "Education"

    # Languages section
    [params.language]
        enable = false
        title = "Languages"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "A software engineer willing to solve problems regardless of tools and technologies. \n\n I have **16+ years** of experience in the software engineering mainly in .Net, web and distributed cloud applications. More than a decade of experience in software architecture."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "Below are the open source projects I have started or contributing to."


    # Skills section
    # This section can be displayed 
    [params.skills]
        enable = true
        showInMain = false
        showInSidebar = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
